language: node_js
node_js:
- node
- lts/*
- '8'
- '6'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: clpo13@gmail.com
  api_key:
    secure: KoDhLzUE+a/sWUA7gwcf8W9OSCHaArpZEhI02uP9A5kHimozFAL+lUWjgcBJn2ajIEdS4DHBKQktT1NLHNs95wygcZ8yAeyZJr95lx5wMd2P7CB5I1ak/y9YcQU1v3q2B28EgqrhQGhLnwC/0G/RGmi9HTPVHV3P5jJIOdh8zpTqeGa+ZrD9thOH7ulqZC9C/7cgM0rtNxE2oYyB8hXOPqYQya2SF3MLQho7tv62tzO7P3nryPuM/fbkhF34qGTtwMy8wsWqx5QwhKsm9nHvmTbTz6HM8Fjo+WXLr8EjdLKugO48ZTcbZHYXG0imq87Dy+lNIYcAXl3AV5VtMEqqySu8xoLpCFe1Oze/0DdlFb32n+ywStGm3sTuknwjGthUj9VyJBZP6XFPbqejDl/nQnPoIa7d9FDPDyzS1SftsW++ympEm/pBOfnPW+qgKuvvVI3FyxwWXKwHzhefY981GLn4nj2FMh7poHYLWMzicehxZh19FHiCLm1Zbs2NfNoCgF+EYdQvDGCY3kCy0jUj5lCRyiVikCb8Qx4xKCo44PhBfAVrSa1yuh89nJvayiIqa0s6SF1hv7HbL7ZGMR1qeoTlZ89w+vLjG5GmUhrb7kRmSQPGtjjDpO/gdRtoB4xQU9pqMAilndDTeT7WZA0rC2PbA3p3QUCAOvhowPtz+0g=
  on:
    tags: true
    repo: clpo13/rangecalc-js
after_success: npm run coverage
